/*--------------- Casas --------------- */

import Casa1 from "../../public/images/casas/casa1/casa1.jpg";
import Casa2 from "../../public/images/casas/casa2/casa2.jpg";
import Casa3 from "../../public/images/casas/casa3/casa3.jpg";
import Casa4 from "../../public/images/casas/casa4/casa4.jpg";
import Casa5 from "../../public/images/casas/casa5/casa5.jpg";
import Casa6 from "../../public/images/casas/casa6/casa6.jpg";
import Casa7 from "../../public/images/casas/casa7/casa7.jpg";

/*--------------- Aptos --------------- */

import Ap1 from "../../public/images/apartamentos/ap1/ap1.jpg";
import Ap2 from "../../public/images/apartamentos/ap2/ap2.jpg";

export const AllProperties = [
  {
    mainImage: Casa1,
    allImages: [{}],
    name: "Testando",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Casa2,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 1,
    bathrooms: 5,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para vender",
  },
  {
    mainImage: Casa3,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Casa4,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Casa5,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Casa6,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Casa7,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Ap1,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "92 ALLIUM PLACE, ORLANDO FL 32827",
    state: "Para alugar",
  },
  {
    mainImage: Ap2,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Ap2,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Ap2,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
  {
    mainImage: Ap2,
    allImages: {},
    name: "92 ALLIUM PLACE, ORLANDO FL 32827",
    price: 30000,
    garages: 2,
    bathrooms: 1,
    bedrooms: 4,
    city: "Curitiba",
    propertieType: "Apartamento",
    state: "Para alugar",
  },
];
